const CARD_WIDTH = 390;
const CARD_HEIGHT = 180;
const GAP = 15;
const COLUMN_COUNT = 3;
const GRID_WIDTH = COLUMN_COUNT * CARD_WIDTH + (COLUMN_COUNT - 1) * GAP;

export { CARD_HEIGHT, CARD_WIDTH, COLUMN_COUNT, GAP, GRID_WIDTH}